#ifndef NTHFRAME_GLOBAL_H
#define NTHFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IVS3DNTHFRAMEPLUGIN_LIBRARY)
#define NTHFRAME_EXPORT Q_DECL_EXPORT
#else
#define NTHFRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // NTHFRAME_GLOBAL_H
