#ifndef IVS3DPLUGININTERFACE_GLOBAL_H
#define IVS3DPLUGININTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IVS3DPLUGININTERFACE_LIBRARY)
#  define IVS3DPLUGININTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define IVS3DPLUGININTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // IVS3DPLUGININTERFACE_GLOBAL_H
