#ifndef SEMANTICSEGMENTATION_GLOBAL_H
#define SEMANTICSEGMENTATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IVS3DSEMANTICSEGMENTATIONPLUGIN_LIBRARY)
#define SEMANTICSEGMENTATION_EXPORT Q_DECL_EXPORT
#else
#define SEMANTICSEGMENTATION_EXPORT Q_DECL_IMPORT
#endif

#endif // SEMANTICSEGMENTATION_GLOBAL_H
